module Project
  ( findProjectRoot
  , generateProjectFile
  , runCabal
  ) where

import           System.Directory (doesFileExist, getCurrentDirectory,
                                   listDirectory)
import           System.FilePath  (takeDirectory, takeExtension, (</>))
import           SimpleCmd        (cmd_)

stackageProjectFile :: String
stackageProjectFile = "cabal.project.stackage"

-- | Walk up the directory tree from CWD looking for a cabal project root.
-- A root is any directory containing a .cabal file or a cabal.project file.
findProjectRoot :: IO (Maybe FilePath)
findProjectRoot = getCurrentDirectory >>= go
  where
    go dir = do
      found <- hasCabalFiles dir
      if found
        then return (Just dir)
        else do
          let parent = takeDirectory dir
          if parent == dir
            then return Nothing
            else go parent

hasCabalFiles :: FilePath -> IO Bool
hasCabalFiles dir = do
  entries    <- listDirectory dir
  hasProject <- doesFileExist (dir </> "cabal.project")
  let hasDotCabal = any ((== ".cabal") . takeExtension) entries
  return (hasProject || hasDotCabal)

-- | Generate cabal.project.stackage in the project root.
-- It imports the user's cabal.project (if present) then the stackage config.
generateProjectFile :: FilePath -> IO FilePath
generateProjectFile configPath = do
  hasProject <- doesFileExist "cabal.project"
  writeFile stackageProjectFile $ unlines $
    [ "-- Generated by cabal-stackage, do not edit" ]
    ++ [ "import: cabal.project" | hasProject ]
    ++ [ "packages: ." | not hasProject ]
    ++ [ "import: " ++ configPath ]
  return stackageProjectFile

-- | Run cabal with the given project file and arguments.
runCabal :: FilePath -> [String] -> IO ()
runCabal projectFile args =
  cmd_ "cabal" (("--project-file=" ++ projectFile) : args)
